config/routes.rb
BroKCupid::Application.routes.draw do
  resources :reservations
  resources :events
  resources :friendships
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :questions
  resources :user_answers

  root :to => 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_question', to: 'questions#new',via: 'get'
  match '/answer_questions', to: 'questions#index', via: 'get'
  match '/create_event', to: 'events#new', via: 'get'
  match '/event_list', to: 'events#index', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @post = current_user.posts.build
      #@post = Post.all
      #@feed_items = current_user.feed.paginate(page: params[:page])
      @feed_items = current_user.friend_feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Bro-k Cupid') %>
<h1>About Bro-k Cupid</h1>
<p>
    Blah
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Contact blah
</p>

app/views/static_pages/help.html.erb
<%= render 'layouts/header' %>
<% provide(:title, 'Help') %>
<div style="width: 500px; margin-left: auto; margin-right: auto;">
  <div class="row">
    <h3 class="title">Help</h3>
    <h5 class="title">Having trouble with the site? Don't know what to do next? Feel free to contact us at socmodder@gmail.com.</h5>

  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <%= render 'layouts/header' %>
    
    <div class="row">
        <aside class="span4">

        <section style="margin-top: 50px;">
            <%= render 'shared/post_form' %>
        </section>
        </aside>
        <div class="span8">
            <h3>Bro Feed</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>

<% else %>
<div class="center hero-unit">
        <h1>Welcome to Bro-k Cupid</h1>

        <h2>
            A Brocial Network
        </h2>

    
    <%= link_to "Sign up now", signup_path, class: "submit" %>
    <%= link_to "Sign in",      signin_path, class: "submit" %>
</div>

<% end %>