config/routes.rb
BroKCupid::Application.routes.draw do
  resources :reservations
  resources :events
  resources :friendships
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :questions
  resources :user_answers

  root :to => 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_question', to: 'questions#new',via: 'get'
  match '/answer_questions', to: 'questions#index', via: 'get'
  match '/create_event', to: 'events#new', via: 'get'
  match '/event_list', to: 'events#index', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :reservations, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :user_answers

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  attr_accessible :email, :first_name, :last_name, :name, :password, :password_confirmation 
  validates(:name, presence: true, length: {maximum: 50})
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true,
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false})
  has_secure_password
  validates :password, length: {minimum: 6}

  scope :without_user, lambda { |user| user ? {:conditions => ["id != ?", user.id]} : {} }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    Post.where("user_id = ?", id)
  end

  def friend_feed
    Post.from_friends(self)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def index
    @bros = User.without_user(current_user).all
    @scores = Hash.new
    @weights = Hash.new
    @weights[1] = 0
    @weights[2] = 1
    @weights[3] = 10
    @weights[4] = 50
    @weights[5] = 100


    @user = current_user
    for bro in @bros do
        diff = 0
        comparedTotal1 = 0
        comparedTotal2 = 0
        total1 = 0
        total2 = 0
        for user_ans in @user.user_answers do
            for bros_ans in bro.user_answers do
                if user_ans.question_id == bros_ans.question_id
                    diff = 5 - (user_ans.answer.to_i - bros_ans.answer.to_i).abs
                    comparedTotal1 += diff * @weights[user_ans.importance.to_i]
                    comparedTotal2 += diff * @weights[bros_ans.importance.to_i]
                    total1 += 5 * @weights[user_ans.importance.to_i]
                    total2 += 5 * @weights[bros_ans.importance.to_i]
                end
            end
        end
        if total1 == 0 or total2 == 0
          @scores[bro.id] = 0
        else
          @scores[bro.id] = ( Math.sqrt( (comparedTotal1.to_f/total1.to_f) * (comparedTotal2.to_f/total2.to_f) ) * 100 )
        end
    end


    @users = User.without_user(current_user).paginate(:order =>"name ASC", :page=> params[:page])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Bro-k Cupid"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    #@user = User.where(:id => params[:id]).first
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  #def signed_in_user
  #    unless signed_in?
  #        store_location
  #        redirect_to signin_url, notice: "Please sign in."
  #    end
  #end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 52 %>
    <%= link_to user.name, user %>
    <% if !current_user.friendships.where(friend_id: user.id).exists? && !user.friendships.where(friend_id: current_user.id).exists? %>
        | <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
    <% end %>
    
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                                        data: { confirm: "You sure?" } %>

    <% end %>
    | Brofficiency Score: <%= @scores[user.id].to_i  %>%
    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%= render 'layouts/header' %>
<center><h3>Update your profile</h3></center>
<br/>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, :class => "fieldlabel" %>
        <%= f.text_field :name, :class => "textfield" %> <br/>

        <%= f.label :email, :class => "fieldlabel" %>
        <%= f.text_field :email, :class => "textfield" %> <br/>

        <%= f.label :password, :class => "fieldlabel" %>
        <%= f.password_field :password, :class => "textfield" %> <br/>

        <%= f.label :password_confirmation, "Confirm Password", :class => "fieldlabel" %>
        <%= f.password_field :password_confirmation, :class => "textfield" %> <br/>

        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">change</a> <br/> <br/>
        <hr/>
        <%= f.submit "Save changes", class: "submit", :style => "float: right" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Bros</h1>

<%= render 'layouts/header' %>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="span6 offset5">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
          <p>
            <%= f.label :name %>
            <%= f.text_field :name %>
          </p>

          <p>
            <%= f.label :email %>
            <%= f.text_field :email %>
          </p>

          <p>
            <%= f.label :password %>
            <%= f.password_field :password %>
          </p>

          <p>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
          </p>

          <p>
            <%= f.submit "Create my account", class: "submit" %>
          </p>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<% provide(:title, @user.name) %>
<div class="row">
    <aside class="span4">
    <section>
        <%= render 'shared/user_info' %>
    </section>
    <section>
        <h2>Friends</h2>
        <ul>
            <% for friendship in @user.friendships %>
                <li>
                    <%= link_to friendship.friend.name, friendship.friend %>
                    (<%= link_to "remove", friendship_path(:nested=>{:inverse => false, :friend_id => friendship.friend.id, :friendship=>friendship}), :method => :delete %>)
                    </li>
                <% end %>

            <% for user in @user.inverse_friends %>
                <li>
                <%= link_to user.name, user %>
                (<%= link_to "remove", friendship_path(:nested=>{:inverse => true, :friend_id => user.id, :friendship=>nil}), :method => :delete %>)
                </li>
            <% end %>
            </ul>
    </section>
    
    </aside>

    <div class="span8">
        <% if @user.posts.any? %>
            <h3><%= @user.name %>'s Posts (<%= @user.posts.count %>)</h3>
            <ol class="posts">
                <%= render @posts %>
            </ol>
            <%= will_paginate @posts %>
        <% end %>
    </div>

</div>

<%= render 'layouts/footer' %>