config/routes.rb
BroKCupid::Application.routes.draw do
  resources :reservations
  resources :events
  resources :friendships
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :questions
  resources :user_answers

  root :to => 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_question', to: 'questions#new',via: 'get'
  match '/answer_questions', to: 'questions#index', via: 'get'
  match '/create_event', to: 'events#new', via: 'get'
  match '/event_list', to: 'events#index', via: 'get'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :event
  belongs_to :attendee, :class_name => "User"

  attr_accessible :event_id, :attendee_id
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @event = Event.find(params[:event_id])
    @reservation = @event.reservations.build(:attendee_id => params[:attendee_id])
    if @reservation.save
      redirect_to @event, :success => "Dope event, bro!"
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(params[:reservation])
      redirect_to @reservation, :notice => "Dat Update, yo!"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_url, :notice => "Yeah, that event was wack."
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </p>
  <p>
    <%= f.label :attendee_id %><br />
    <%= f.number_field :attendee_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/reservations/edit.html.erb
<% title "Edit Reservation" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @reservation %> |
  <%= link_to "View All", reservations_path %>
</p>

app/views/reservations/index.html.erb
<% title "Reservations" %>

<table>
  <tr>
    <th>Event</th>
    <th>Attendee</th>
  </tr>
  <% for reservation in @reservations %>
    <tr>
      <td><%= reservation.event_id %></td>
      <td><%= reservation.attendee_id %></td>
      <td><%= link_to "Show", reservation %></td>
      <td><%= link_to "Edit", edit_reservation_path(reservation) %></td>
      <td><%= link_to "Destroy", reservation, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Reservation", new_reservation_path %></p>

app/views/reservations/new.html.erb
<% title "New Reservation" %>

<%= render 'form' %>

<p><%= link_to "Back to List", reservations_path %></p>

app/views/reservations/show.html.erb
<% title "Reservation" %>

<p>
  <strong>Event:</strong>
  <%= @reservation.event_id %>
</p>
<p>
  <strong>Attendee:</strong>
  <%= @reservation.attendee_id %>
</p>

<p>
  <%= link_to "Edit", edit_reservation_path(@reservation) %> |
  <%= link_to "Destroy", @reservation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", reservations_path %>
</p>