config/routes.rb
BroKCupid::Application.routes.draw do
  resources :reservations
  resources :events
  resources :friendships
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :questions
  resources :user_answers

  root :to => 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_question', to: 'questions#new',via: 'get'
  match '/answer_questions', to: 'questions#index', via: 'get'
  match '/create_event', to: 'events#new', via: 'get'
  match '/event_list', to: 'events#index', via: 'get'

end

app/views/layouts/_debug.html.erb
<!-- Debug Info -->
<body>
    <div class="container">
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_footer.html.erb
<footer>
    <p>&copy; Bro-k Cupid 2013</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>
      $(".dropdown-menu").ready(function () {
          $(".dropdown-menu li a").mouseover(function () {
              $(this).css("background-color", "#FBAFE3");
              $(this).css("color", "#000");
          });
          $(".dropdown-menu li a").mouseleave(function () {
              $(this).css("background-color", "#FFF");
              $(this).css("color", "#000");
          });
      });
  </script>
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Bro-K Cupid", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <% else %>
          <li><%= link_to "Home", current_user %></li>
          <% end %>

          <% if signed_in? %>
              <li><%= link_to "Find Bros", users_path %></li>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Events <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Create Event", new_event_path %></li>
                  <li><%= link_to "Find Event", events_path %></li>
                </ul>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Matching <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Create Topic", new_question_path %></li>
                  <li><%= link_to "View Topics", questions_path %></li>
                </ul>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
              <li><%= link_to "Help", help_path %></li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_headerOLD.html.erb
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Bro-K Cupid</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Find Bros", "/path1"  %></li>
              <li><%= link_to "Events",    "/path2"  %></li>
              <li><%= link_to "Questions", "/path3"  %></li>
           </ul>
          </div><!--/.nav-collapse-->
        </div>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endof]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BroKCupid" %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= render 'layouts/shim' %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
    </div>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

    <% render 'layouts/debug' %>

  </body>
</html>